Repository Vonage/vonage-php-sdk-core, pull requests merged in 2022-01, with the labels that each got.

#303 Allow psr/log 2.0 (#299)
  composer.json
Labels: pending-review, dont-merge

#302 Country code prefix fix for Number Insight
  src/Insights/Basic.php
  test/Insights/BasicTest.php
Labels: bug, pending-review, dont-merge

#305 Feature/further removals
  src/Account/Price.php
  src/Application/Application.php
  src/Application/Client.php
  src/Voice/Message/Callback.php
  src/Voice/Message/Message.php
  src/Voice/NCCO/Action/Talk.php
  test/Application/ClientTest.php
  test/Voice/Message/CallbackTest.php
  test/Voice/Message/MessageTest.php
  test/Voice/NCCO/Action/TalkTest.php
Labels: pending-review

#307 Feature/array access deprecations
  src/Account/Balance.php
  src/Account/Config.php
  src/Account/Price.php
  src/Account/Secret.php
  src/Account/SecretCollection.php
  src/Application/Client.php
  src/Client/Credentials/AbstractCredentials.php
  src/Client/Credentials/Container.php
  src/Client/Credentials/CredentialsInterface.php
  src/Client/Credentials/Handler/SignatureBodyFormHandler.php
  src/Client/Credentials/Handler/SignatureBodyHandler.php
  src/Client/Credentials/Handler/SignatureQueryHandler.php
  src/Insights/Basic.php
  src/Message/Message.php
  src/Network.php
  src/Verify/Verification.php
  test/Account/BalanceTest.php
  test/Account/ClientTest.php
  test/Account/ConfigTest.php
  test/Account/PrefixPriceTest.php
  test/Account/SecretCollectionTest.php
  test/Account/SecretTest.php
  test/Account/SmsPriceTest.php
  test/Application/ClientTest.php
  test/Client/Credentials/BasicTest.php
  test/Client/Credentials/ContainerTest.php
  test/Client/Credentials/KeypairTest.php
  test/Client/Credentials/OAuthTest.php
  test/Insights/AdvancedTest.php
  test/Insights/BasicTest.php
  test/Insights/CnamTraitTest.php
  test/Insights/StandardTest.php
  test/Message/FetchedMessageTest.php
  test/Message/MultiMessageTest.php
  test/NetworkTest.php
  test/Verify/VerificationTest.php
Labels: pending-review
