Repository Vonage/vonage-php-sdk-core, pull requests merged in 2023-10, with the labels that each got.

#438 Network code optional in DeliveryReceipt
  src/SMS/Webhook/DeliveryReceipt.php
Labels: bug, release-candidate

#439 add permissions to take out write-all in CI
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: enhancement, release-candidate

#441 Refactor to JWT library
  composer.json
  src/Client/Credentials/Keypair.php
  test/Client/Credentials/KeypairTest.php
Labels: enhancement, release-candidate

#443 Add null check for appId getter on Number model
  src/Numbers/Number.php
Labels: bug

#445 New Verify V2 Locales
  src/Verify2/VerifyObjects/VerificationLocale.php
  test/Client/Credentials/KeypairTest.php
Labels: release-candidate

#448 Allow to do numbers filtering with has_application and application_id filters
  src/Numbers/Filter/AvailableNumbers.php
  test/Numbers/Filter/AvailableNumbersTest.php
Labels: bug
